export const INSTITUTION_CATEGORIES = [
  { id: 'all', label: 'הכל', labelEn: 'All' },
  { id: 'bank', label: 'בנקים', labelEn: 'Banks' },
  { id: 'credit', label: 'כרטיסי אשראי', labelEn: 'Credit Cards' },
  { id: 'food_perks', label: 'הסעדה והטבות', labelEn: 'Food & Perks' },
  { id: 'savings', label: 'גמל, פנסיה והשקעות', labelEn: 'Provident & Investments' },
  { id: 'wallet', label: 'ארנק ומזומן', labelEn: 'Wallet' },
];

export const ISRAELI_INSTITUTIONS = [
  // ── 1. WALLET / CASH ──────────────────────────────────────────────────────
  {
    id: 'wallet',
    name: 'ארנק מזומנים',
    nameEn: 'Cash Wallet',
    type: 'wallet',
    category: 'wallet',
    color: '#10b981',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    logoText: 'ארנק',
    fields: [],
    labels: {},
    isScrapable: false,
    description: 'מעקב הוצאות ומשיכות במזומן',
  },

  // ── 2. BANKS (ISRAELI BANK SCRAPERS) ──────────────────────────────────────
  {
    id: 'hapoalim',
    name: 'בנק הפועלים',
    nameEn: 'Bank Hapoalim',
    type: 'bank',
    category: 'bank',
    color: '#dc2626',
    badgeBg: 'rgba(220, 38, 38, 0.15)',
    logoText: 'הפועלים',
    fields: ['userCode', 'password'],
    labels: { userCode: 'קוד משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'leumi',
    name: 'בנק לאומי',
    nameEn: 'Bank Leumi',
    type: 'bank',
    category: 'bank',
    color: '#2563eb',
    badgeBg: 'rgba(37, 99, 235, 0.15)',
    logoText: 'לאומי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'discount',
    name: 'בנק דיסקונט',
    nameEn: 'Discount Bank',
    type: 'bank',
    category: 'bank',
    color: '#059669',
    badgeBg: 'rgba(5, 150, 105, 0.15)',
    logoText: 'דיסקונט',
    fields: ['idNumber', 'password', 'num'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה', num: 'קוד מזהה' },
    isScrapable: true,
  },
  {
    id: 'mizrahi',
    name: 'בנק מזרחי טפחות',
    nameEn: 'Mizrahi Tefahot',
    type: 'bank',
    category: 'bank',
    color: '#ea580c',
    badgeBg: 'rgba(234, 88, 12, 0.15)',
    logoText: 'מזרחי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'mercantile',
    name: 'בנק מרכנתיל',
    nameEn: 'Mercantile Bank',
    type: 'bank',
    category: 'bank',
    color: '#0d9488',
    badgeBg: 'rgba(13, 148, 136, 0.15)',
    logoText: 'מרכנתיל',
    fields: ['idNumber', 'password', 'num'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה', num: 'קוד מזהה' },
    isScrapable: true,
  },
  {
    id: 'otsarHahayal',
    name: 'אוצר החייל',
    nameEn: 'Otsar Hahayal',
    type: 'bank',
    category: 'bank',
    color: '#4f46e5',
    badgeBg: 'rgba(79, 70, 229, 0.15)',
    logoText: 'אוצר החייל',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'beinleumi',
    name: 'הבנק הבינלאומי (FIBI)',
    nameEn: 'First International Bank',
    type: 'bank',
    category: 'bank',
    color: '#0891b2',
    badgeBg: 'rgba(8, 145, 178, 0.15)',
    logoText: 'בינלאומי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'massad',
    name: 'בנק מסד',
    nameEn: 'Massad Bank',
    type: 'bank',
    category: 'bank',
    color: '#ca8a04',
    badgeBg: 'rgba(202, 138, 4, 0.15)',
    logoText: 'מסד',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'yahav',
    name: 'בנק יהב',
    nameEn: 'Bank Yahav',
    type: 'bank',
    category: 'bank',
    color: '#059669',
    badgeBg: 'rgba(5, 150, 105, 0.15)',
    logoText: 'יהב',
    fields: ['username', 'idNumber', 'password'],
    labels: { username: 'שם משתמש', idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'oneZero',
    name: 'וואן זירו (OneZero)',
    nameEn: 'OneZero Digital Bank',
    type: 'bank',
    category: 'bank',
    color: '#111827',
    badgeBg: 'rgba(255, 255, 255, 0.15)',
    logoText: 'OneZero',
    fields: ['email', 'password', 'phoneNumber'],
    labels: { email: 'אימייל', password: 'סיסמה', phoneNumber: 'מספר טלפון' },
    isScrapable: true,
  },
  {
    id: 'union',
    name: 'בנק אגוד',
    nameEn: 'Union Bank',
    type: 'bank',
    category: 'bank',
    color: '#7c3aed',
    badgeBg: 'rgba(124, 58, 237, 0.15)',
    logoText: 'אגוד',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: true,
  },

  // ── 3. CREDIT CARDS (ISRAELI BANK SCRAPERS) ───────────────────────────────
  {
    id: 'max',
    name: 'מקס (Max)',
    nameEn: 'Max It',
    type: 'credit',
    category: 'credit',
    color: '#0284c7',
    badgeBg: 'rgba(2, 132, 199, 0.15)',
    logoText: 'Max',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש / מייל', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'visaCal',
    name: 'כאל (Visa Cal)',
    nameEn: 'Visa Cal',
    type: 'credit',
    category: 'credit',
    color: '#e11d48',
    badgeBg: 'rgba(225, 29, 72, 0.15)',
    logoText: 'Cal',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש / מייל', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'isracard',
    name: 'ישראכרט',
    nameEn: 'Isracard',
    type: 'credit',
    category: 'credit',
    color: '#16a34a',
    badgeBg: 'rgba(22, 163, 74, 0.15)',
    logoText: 'ישראכרט',
    fields: ['idNumber', 'cardLast4', 'password'],
    labels: { idNumber: 'תעודת זהות', cardLast4: '4 ספרות אחרונות', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'amex',
    name: 'אמריקן אקספרס',
    nameEn: 'American Express',
    type: 'credit',
    category: 'credit',
    color: '#0369a1',
    badgeBg: 'rgba(3, 105, 161, 0.15)',
    logoText: 'Amex',
    fields: ['idNumber', 'cardLast4', 'password'],
    labels: { idNumber: 'תעודת זהות', cardLast4: '4 ספרות אחרונות', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'beyhadBishvilha',
    name: 'ביחד בשבילך',
    nameEn: 'Beyhad Bishvilha',
    type: 'credit',
    category: 'credit',
    color: '#d97706',
    badgeBg: 'rgba(217, 119, 6, 0.15)',
    logoText: 'ביחד',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: true,
  },
  {
    id: 'behatsdaa',
    name: 'בהצדעה',
    nameEn: 'Behatsdaa',
    type: 'credit',
    category: 'credit',
    color: '#475569',
    badgeBg: 'rgba(71, 85, 105, 0.15)',
    logoText: 'בהצדעה',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: true,
  },

  // ── 4. FOOD CARDS & PERKS ─────────────────────────────────────────────────
  {
    id: 'cibus',
    name: 'סיבוס (Pluxee / Cibus)',
    nameEn: 'Cibus Pluxee',
    type: 'wallet',
    category: 'food_perks',
    color: '#059669',
    badgeBg: 'rgba(5, 150, 105, 0.15)',
    logoText: 'סיבוס',
    fields: ['email', 'password'],
    labels: { email: 'מייל / שם משתמש בסיבוס', password: 'סיסמה' },
    isScrapable: false,
    description: 'כרטיס הסעדה ותקציב ארוחות יומי/חודשי',
  },
  {
    id: 'tenbis',
    name: 'תן ביס (10bis)',
    nameEn: '10bis',
    type: 'wallet',
    category: 'food_perks',
    color: '#f97316',
    badgeBg: 'rgba(249, 115, 22, 0.15)',
    logoText: '10bis',
    fields: ['email', 'password'],
    labels: { email: 'אימייל בתן ביס', password: 'סיסמה' },
    isScrapable: false,
    description: 'כרטיס תן ביס ותקציב מסעדות',
  },
  {
    id: 'buyme',
    name: 'ביימי (BuyMe)',
    nameEn: 'BuyMe',
    type: 'wallet',
    category: 'food_perks',
    color: '#ec4899',
    badgeBg: 'rgba(236, 72, 153, 0.15)',
    logoText: 'BuyMe',
    fields: ['phoneNumber', 'password'],
    labels: { phoneNumber: 'מספר טלפון', password: 'סיסמה' },
    isScrapable: false,
    description: 'כרטיסי מתנה וגיפט קארד',
  },

  // ── 5. PROVIDENT, PENSION & INVESTMENT FUNDS ─────────────────────────────
  {
    id: 'altshuler',
    name: 'אלטשולר שחם',
    nameEn: 'Altshuler Shaham',
    type: 'savings',
    category: 'savings',
    color: '#1e3a8a',
    badgeBg: 'rgba(30, 58, 138, 0.15)',
    logoText: 'אלטשולר',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'קופת גמל, קרן השתלמות וחיסכון לכל ילד',
  },
  {
    id: 'meitav',
    name: 'מיטב דש (Meitav)',
    nameEn: 'Meitav Dash',
    type: 'savings',
    category: 'savings',
    color: '#0284c7',
    badgeBg: 'rgba(2, 132, 199, 0.15)',
    logoText: 'מיטב',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'גמל, השתלמות, פנסיה ומסחר עצמאי',
  },
  {
    id: 'migdal',
    name: 'מגדל ביטוח ופנסיה',
    nameEn: 'Migdal Insurance & Pension',
    type: 'savings',
    category: 'savings',
    color: '#047857',
    badgeBg: 'rgba(4, 120, 87, 0.15)',
    logoText: 'מגדל',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'קרן פנסיה, ביטוח מנהלים וגמל',
  },
  {
    id: 'harel',
    name: 'הראל ביטוח ופיננסים',
    nameEn: 'Harel Insurance & Finance',
    type: 'savings',
    category: 'savings',
    color: '#2563eb',
    badgeBg: 'rgba(37, 99, 235, 0.15)',
    logoText: 'הראל',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'פנסיה, גמל והשתלמות',
  },
  {
    id: 'phoenix',
    name: 'הפניקס',
    nameEn: 'The Phoenix',
    type: 'savings',
    category: 'savings',
    color: '#d97706',
    badgeBg: 'rgba(217, 119, 6, 0.15)',
    logoText: 'הפניקס',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'גמל, השתלמות, פנסיה וחיסכון',
  },
  {
    id: 'menora',
    name: 'מנורה מבטחים',
    nameEn: 'Menora Mivtachim',
    type: 'savings',
    category: 'savings',
    color: '#0369a1',
    badgeBg: 'rgba(3, 105, 161, 0.15)',
    logoText: 'מנורה',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'קרן הפנסיה הגדולה בישראל, גמל והשתלמות',
  },
  {
    id: 'clal',
    name: 'כלל ביטוח ופנסיה',
    nameEn: 'Clal Insurance & Finance',
    type: 'savings',
    category: 'savings',
    color: '#1d4ed8',
    badgeBg: 'rgba(29, 78, 216, 0.15)',
    logoText: 'כלל',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'פנסיה, גמל והשתלמות',
  },
  {
    id: 'yelin',
    name: 'ילין לפידות',
    nameEn: 'Yelin Lapidot',
    type: 'savings',
    category: 'savings',
    color: '#854d0e',
    badgeBg: 'rgba(133, 77, 14, 0.15)',
    logoText: 'ילין',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'קופות גמל וקרנות השתלמות',
  },
  {
    id: 'more',
    name: 'מור השקעות',
    nameEn: 'More Investments',
    type: 'savings',
    category: 'savings',
    color: '#0f766e',
    badgeBg: 'rgba(15, 118, 110, 0.15)',
    logoText: 'מור',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
    isScrapable: false,
    description: 'קופת גמל להשקעה, השתלמות ופנסיה',
  },
  {
    id: 'gemel',
    name: 'קופת גמל / קרן השתלמות כללית',
    nameEn: 'General Provident & Pension Fund',
    type: 'savings',
    category: 'savings',
    color: '#10b981',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    logoText: 'גמל',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות / מספר עמית', password: 'סיסמה' },
    isScrapable: false,
    description: 'מעקב עצמאי אחר יתרת חיסכון והפקדות',
  },
];

export const getInstitutionById = (id) => {
  return ISRAELI_INSTITUTIONS.find((inst) => inst.id === id) || {
    id,
    name: id,
    nameEn: id,
    type: 'bank',
    category: 'bank',
    color: '#6366f1',
    badgeBg: 'rgba(99, 102, 241, 0.15)',
    logoText: (id || 'TX').substring(0, 3).toUpperCase(),
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
    isScrapable: false,
  };
};
