export const ISRAELI_INSTITUTIONS = [
  {
    id: 'hapoalim',
    name: 'בנק הפועלים',
    nameEn: 'Bank Hapoalim',
    type: 'bank',
    color: '#dc2626',
    badgeBg: 'rgba(220, 38, 38, 0.15)',
    logoText: 'הפועלים',
    fields: ['userCode', 'password'],
    labels: { userCode: 'קוד משתמש', password: 'סיסמה' },
  },
  {
    id: 'leumi',
    name: 'בנק לאומי',
    nameEn: 'Bank Leumi',
    type: 'bank',
    color: '#2563eb',
    badgeBg: 'rgba(37, 99, 235, 0.15)',
    logoText: 'לאומי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'discount',
    name: 'בנק דיסקונט',
    nameEn: 'Discount Bank',
    type: 'bank',
    color: '#059669',
    badgeBg: 'rgba(5, 150, 105, 0.15)',
    logoText: 'דיסקונט',
    fields: ['idNumber', 'password', 'num'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה', num: 'קוד מזהה' },
  },
  {
    id: 'mizrahi',
    name: 'בנק מזרחי טפחות',
    nameEn: 'Mizrahi Tefahot',
    type: 'bank',
    color: '#ea580c',
    badgeBg: 'rgba(234, 88, 12, 0.15)',
    logoText: 'מזרחי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'mercantile',
    name: 'בנק מרכנתיל',
    nameEn: 'Mercantile Bank',
    type: 'bank',
    color: '#0d9488',
    badgeBg: 'rgba(13, 148, 136, 0.15)',
    logoText: 'מרכנתיל',
    fields: ['idNumber', 'password', 'num'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה', num: 'קוד מזהה' },
  },
  {
    id: 'otsarHahayal',
    name: 'אוצר החייל',
    nameEn: 'Otsar Hahayal',
    type: 'bank',
    color: '#4f46e5',
    badgeBg: 'rgba(79, 70, 229, 0.15)',
    logoText: 'אוצר החייל',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'visaCal',
    name: 'כאל (Visa Cal)',
    nameEn: 'Visa Cal',
    type: 'credit',
    color: '#e11d48',
    badgeBg: 'rgba(225, 29, 72, 0.15)',
    logoText: 'Cal',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש / מייל', password: 'סיסמה' },
  },
  {
    id: 'max',
    name: 'מקס (Max)',
    nameEn: 'Max It',
    type: 'credit',
    color: '#0284c7',
    badgeBg: 'rgba(2, 132, 199, 0.15)',
    logoText: 'Max',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'isracard',
    name: 'ישראכרט',
    nameEn: 'Isracard',
    type: 'credit',
    color: '#16a34a',
    badgeBg: 'rgba(22, 163, 74, 0.15)',
    logoText: 'ישראכרט',
    fields: ['idNumber', 'cardLast4', 'password'],
    labels: { idNumber: 'תעודת זהות', cardLast4: '4 ספרות אחרונות', password: 'סיסמה' },
  },
  {
    id: 'amex',
    name: 'אמריקן אקספרס',
    nameEn: 'American Express',
    type: 'credit',
    color: '#0369a1',
    badgeBg: 'rgba(3, 105, 161, 0.15)',
    logoText: 'Amex',
    fields: ['idNumber', 'cardLast4', 'password'],
    labels: { idNumber: 'תעודת זהות', cardLast4: '4 ספרות אחרונות', password: 'סיסמה' },
  },
  {
    id: 'union',
    name: 'בנק אגוד',
    nameEn: 'Union Bank',
    type: 'bank',
    color: '#7c3aed',
    badgeBg: 'rgba(124, 58, 237, 0.15)',
    logoText: 'אגוד',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'beinleumi',
    name: 'הבנק הבינלאומי',
    nameEn: 'First International Bank',
    type: 'bank',
    color: '#0891b2',
    badgeBg: 'rgba(8, 145, 178, 0.15)',
    logoText: 'בינלאומי',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'massad',
    name: 'בנק מסד',
    nameEn: 'Massad Bank',
    type: 'bank',
    color: '#ca8a04',
    badgeBg: 'rgba(202, 138, 4, 0.15)',
    logoText: 'מסד',
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  },
  {
    id: 'yahav',
    name: 'בנק יהב',
    nameEn: 'Bank Yahav',
    type: 'bank',
    color: '#059669',
    badgeBg: 'rgba(5, 150, 105, 0.15)',
    logoText: 'יהב',
    fields: ['username', 'idNumber', 'password'],
    labels: { username: 'שם משתמש', idNumber: 'תעודת זהות', password: 'סיסמה' },
  },
  {
    id: 'oneZero',
    name: 'וואן זירו (OneZero)',
    nameEn: 'OneZero Digital Bank',
    type: 'bank',
    color: '#111827',
    badgeBg: 'rgba(255, 255, 255, 0.15)',
    logoText: 'OneZero',
    fields: ['email', 'password', 'phoneNumber'],
    labels: { email: 'אימייל', password: 'סיסמה', phoneNumber: 'מספר טלפון' },
  },
  {
    id: 'beyhadBishvilha',
    name: 'ביחד בשבילך',
    nameEn: 'Beyhad Bishvilha',
    type: 'credit',
    color: '#d97706',
    badgeBg: 'rgba(217, 119, 6, 0.15)',
    logoText: 'ביחד',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
  },
  {
    id: 'behatsdaa',
    name: 'בהצדעה',
    nameEn: 'Behatsdaa',
    type: 'credit',
    color: '#475569',
    badgeBg: 'rgba(71, 85, 105, 0.15)',
    logoText: 'בהצדעה',
    fields: ['idNumber', 'password'],
    labels: { idNumber: 'תעודת זהות', password: 'סיסמה' },
  },
];

export const getInstitutionById = (id) => {
  return ISRAELI_INSTITUTIONS.find((inst) => inst.id === id) || {
    id,
    name: id,
    nameEn: id,
    type: 'bank',
    color: '#6366f1',
    badgeBg: 'rgba(99, 102, 241, 0.15)',
    logoText: id.substring(0, 3).toUpperCase(),
    fields: ['username', 'password'],
    labels: { username: 'שם משתמש', password: 'סיסמה' },
  };
};
